on:
  - push
  - pull_request

jobs:
  build-sketches:
    runs-on: ubuntu-20.04

    steps:
      # GIT Checkout
      - uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install Libs and Cores
        run: ci/install-deps.sh

      - name: Download sketch
        run: ci/download-sketch.sh
        
      - name: Compile Sketches
        run: ci/sen-wea.sh
